### ISSUE TITLE
Exclude directory

### ISSUE THREAD

**Issue by pasqualevitiello** [rasmusbe/wp-pot-cli#17]
Let's say I want to exclude a specific directory: I've tried with an array like this `--src ['**/*.php', '!dist/**/*.php']` as suggested on [wp-pot docs](https://github.com/rasmusbe/wp-pot) but no success. Any advice?

**Comment by rasmusbe** [comment]
Hi,

If you add the glob as a string, and escape `!` it will work. Example:
`./cli.js --src="['**/*.php', '\!dist/**/*.php']"`
