### ISSUE TITLE
Scan subfolders?

### ISSUE THREAD

**Issue by UVLabs** [rasmusbe/wp-pot-cli#50]
It doesn't seem like the command scans through subfolders, just the top level folder and then creates the translations for the files in that top level folder

**Comment by rasmusbe** [comment]
No, you can use wildcards in the src paths.

**Comment by UVLabs** [comment]
@rasmusbe I believed I tried that can you give an example?

I have php files in the root, then I have php files in the folders that are in the root, and those folders also have folders that have php with translatable strings files in them

**Comment by rasmusbe** [comment]
`wp-pot --src '**/*.php'`
